-- MySQL Script generated by MySQL Workbench
-- Fri Dec 14 21:06:51 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema szbd_projekt
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema szbd_projekt
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `szbd_projekt` DEFAULT CHARACTER SET utf8 ;
USE `szbd_projekt` ;

-- -----------------------------------------------------
-- Table `szbd_projekt`.`adress`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `szbd_projekt`.`adress` ;

CREATE TABLE IF NOT EXISTS `szbd_projekt`.`adress` (
  `id_adress` INT NOT NULL AUTO_INCREMENT,
  `country` VARCHAR(45) NOT NULL,
  `province` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `street` VARCHAR(45) NOT NULL,
  `house_number` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id_adress`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `szbd_projekt`.`rental_office`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `szbd_projekt`.`rental_office` ;

CREATE TABLE IF NOT EXISTS `szbd_projekt`.`rental_office` (
  `id_rental_office` INT NOT NULL AUTO_INCREMENT,
  `rental_office_name` VARCHAR(45) NOT NULL,
  `id_adress` INT NOT NULL,
  PRIMARY KEY (`id_rental_office`, `id_adress`),
  UNIQUE INDEX `idrental_office_UNIQUE` (`id_rental_office` ASC) VISIBLE,
  UNIQUE INDEX `rental_office_name_UNIQUE` (`rental_office_name` ASC) VISIBLE,
  INDEX `fk_rental_office_adress1_idx` (`id_adress` ASC) VISIBLE,
  UNIQUE INDEX `id_adress_UNIQUE` (`id_adress` ASC) VISIBLE,
  CONSTRAINT `fk_rental_office_adress1`
    FOREIGN KEY (`id_adress`)
    REFERENCES `szbd_projekt`.`adress` (`id_adress`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `szbd_projekt`.`employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `szbd_projekt`.`employee` ;

CREATE TABLE IF NOT EXISTS `szbd_projekt`.`employee` (
  `id_employee` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `position` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `id_rental_office` INT NOT NULL,
  `id_adress` INT NOT NULL,
  PRIMARY KEY (`id_employee`, `id_rental_office`, `id_adress`),
  INDEX `fk_employees_rental_office_idx` (`id_rental_office` ASC) VISIBLE,
  UNIQUE INDEX `id_employee_UNIQUE` (`id_employee` ASC) VISIBLE,
  INDEX `fk_employee_adress1_idx` (`id_adress` ASC) VISIBLE,
  UNIQUE INDEX `id_adress_UNIQUE` (`id_adress` ASC) VISIBLE,
  CONSTRAINT `fk_employees_rental_office`
    FOREIGN KEY (`id_rental_office`)
    REFERENCES `szbd_projekt`.`rental_office` (`id_rental_office`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_adress1`
    FOREIGN KEY (`id_adress`)
    REFERENCES `szbd_projekt`.`adress` (`id_adress`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `szbd_projekt`.`client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `szbd_projekt`.`client` ;

CREATE TABLE IF NOT EXISTS `szbd_projekt`.`client` (
  `id_client` INT NOT NULL AUTO_INCREMENT,
  `client_first_name` VARCHAR(45) NOT NULL,
  `client_last_name` VARCHAR(45) NOT NULL,
  `registration_date` DATETIME NOT NULL,
  `email` VARCHAR(45) NULL,
  `number` INT NULL,
  `id_rental_office` INT NOT NULL,
  `id_adress` INT NOT NULL,
  PRIMARY KEY (`id_client`, `id_rental_office`, `id_adress`),
  INDEX `fk_client_rental_office1_idx` (`id_rental_office` ASC) VISIBLE,
  INDEX `fk_client_adress1_idx` (`id_adress` ASC) VISIBLE,
  UNIQUE INDEX `id_adress_UNIQUE` (`id_adress` ASC) VISIBLE,
  CONSTRAINT `fk_client_rental_office1`
    FOREIGN KEY (`id_rental_office`)
    REFERENCES `szbd_projekt`.`rental_office` (`id_rental_office`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_client_adress1`
    FOREIGN KEY (`id_adress`)
    REFERENCES `szbd_projekt`.`adress` (`id_adress`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `szbd_projekt`.`genre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `szbd_projekt`.`genre` ;

CREATE TABLE IF NOT EXISTS `szbd_projekt`.`genre` (
  `genre_name` VARCHAR(45) NOT NULL,
  `genre_description` VARCHAR(400) NULL,
  PRIMARY KEY (`genre_name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `szbd_projekt`.`movie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `szbd_projekt`.`movie` ;

CREATE TABLE IF NOT EXISTS `szbd_projekt`.`movie` (
  `id_movie` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `director` VARCHAR(45) NOT NULL,
  `length` INT NOT NULL,
  `rating` DECIMAL(3,1) NULL,
  `description` VARCHAR(200) NULL,
  `genre_name` VARCHAR(45) NULL,
  PRIMARY KEY (`id_movie`),
  INDEX `fk_movie_genre1_idx` (`genre_name` ASC) VISIBLE,
  CONSTRAINT `fk_movie_genre1`
    FOREIGN KEY (`genre_name`)
    REFERENCES `szbd_projekt`.`genre` (`genre_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `szbd_projekt`.`rentals`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `szbd_projekt`.`rentals` ;

CREATE TABLE IF NOT EXISTS `szbd_projekt`.`rentals` (
  `id_rental` INT NOT NULL AUTO_INCREMENT,
  `rental_date` DATETIME NOT NULL,
  `return_date` DATETIME NULL,
  `id_client` INT NOT NULL,
  `id_employee` INT NOT NULL,
  `id_movie` INT NOT NULL,
  PRIMARY KEY (`id_rental`, `id_client`, `id_employee`, `id_movie`),
  UNIQUE INDEX `id_rental_UNIQUE` (`id_rental` ASC) VISIBLE,
  INDEX `fk_rentals_clients1_idx` (`id_client` ASC) VISIBLE,
  INDEX `fk_rentals_employee1_idx` (`id_employee` ASC) VISIBLE,
  INDEX `fk_rentals_movie1_idx` (`id_movie` ASC) VISIBLE,
  CONSTRAINT `fk_rentals_clients1`
    FOREIGN KEY (`id_client`)
    REFERENCES `szbd_projekt`.`client` (`id_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rentals_employee1`
    FOREIGN KEY (`id_employee`)
    REFERENCES `szbd_projekt`.`employee` (`id_employee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rentals_movie1`
    FOREIGN KEY (`id_movie`)
    REFERENCES `szbd_projekt`.`movie` (`id_movie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `szbd_projekt`.`actor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `szbd_projekt`.`actor` ;

CREATE TABLE IF NOT EXISTS `szbd_projekt`.`actor` (
  `id_actor` INT NOT NULL AUTO_INCREMENT,
  `actor_first_name` VARCHAR(45) NOT NULL,
  `actor_last_name` VARCHAR(45) NOT NULL,
  `date_of_birth` DATETIME NULL,
  PRIMARY KEY (`id_actor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `szbd_projekt`.`cast`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `szbd_projekt`.`cast` ;

CREATE TABLE IF NOT EXISTS `szbd_projekt`.`cast` (
  `id_actor` INT NOT NULL,
  `actor_rating` DECIMAL(3,1) NULL,
  `characters` VARCHAR(100) NULL,
  `id_movie` INT NOT NULL,
  PRIMARY KEY (`id_actor`, `id_movie`),
  INDEX `fk_cast_actor1_idx` (`id_actor` ASC) VISIBLE,
  INDEX `fk_cast_movie1_idx` (`id_movie` ASC) VISIBLE,
  CONSTRAINT `fk_cast_actor1`
    FOREIGN KEY (`id_actor`)
    REFERENCES `szbd_projekt`.`actor` (`id_actor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cast_movie1`
    FOREIGN KEY (`id_movie`)
    REFERENCES `szbd_projekt`.`movie` (`id_movie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `szbd_projekt`.`movies_warehouse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `szbd_projekt`.`movies_warehouse` ;

CREATE TABLE IF NOT EXISTS `szbd_projekt`.`movies_warehouse` (
  `id_warehouse` INT NOT NULL AUTO_INCREMENT,
  `quantity` INT NOT NULL,
  `charge` DECIMAL(5,2) NOT NULL,
  `id_rental_office` INT NOT NULL,
  `id_movie` INT NOT NULL,
  PRIMARY KEY (`id_warehouse`, `id_rental_office`, `id_movie`),
  INDEX `fk_movies_warehouse_rental_office1_idx` (`id_rental_office` ASC) VISIBLE,
  INDEX `fk_movies_warehouse_movie1_idx` (`id_movie` ASC) VISIBLE,
  CONSTRAINT `fk_movies_warehouse_rental_office1`
    FOREIGN KEY (`id_rental_office`)
    REFERENCES `szbd_projekt`.`rental_office` (`id_rental_office`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movies_warehouse_movie1`
    FOREIGN KEY (`id_movie`)
    REFERENCES `szbd_projekt`.`movie` (`id_movie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `szbd_projekt`.`rental_element`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `szbd_projekt`.`rental_element` ;

CREATE TABLE IF NOT EXISTS `szbd_projekt`.`rental_element` (
  `amount_of_rentals` INT NOT NULL,
  `id_warehouse` INT NOT NULL,
  `id_rental` INT NOT NULL,
  PRIMARY KEY (`id_warehouse`, `id_rental`),
  INDEX `fk_rental_element_rentals1_idx` (`id_rental` ASC) VISIBLE,
  CONSTRAINT `fk_rental_element_movies_warehouse1`
    FOREIGN KEY (`id_warehouse`)
    REFERENCES `szbd_projekt`.`movies_warehouse` (`id_warehouse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rental_element_rentals1`
    FOREIGN KEY (`id_rental`)
    REFERENCES `szbd_projekt`.`rentals` (`id_rental`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
